config/routes.rb
PQRLicensor::Application.routes.draw do
  # Default landing page.
  root                          to: 'static_pages#home'
  # Rewriting of statics.
  match       '/home',          to: 'static_pages#home'
  match       '/how_it_works',  to: 'static_pages#how_it_works'
  # Rewriting of sign-up / sign-in.
  match       '/signup',        to: 'users#new'
  match       '/signin',        to: 'sessions#new'
  match       '/signout',       to: 'sessions#destroy', via: :delete
  match       '/sessions/my',   to: 'sessions#my'
  resources   :sessions,        only: [ :new, :my, :create, :destroy ]
  # Password resets...
  get         'password_resets/new'
  resources   :password_resets
  # Resources access.
  resources   :sessions,  only: [ :new, :create, :destroy ]
  resources   :users do
    resources   :hardware_tags
    resources   :licenses
  end
  resources   :software_tags
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	# Definition for the Home static page.
 	def home
  	end
	# Definition for the About static page.
  def how_it_works
  end
end

app/views/static_pages/home.haml
.center.hero-unit
  %h1 Welcome
  %h2
    This is the main page for the
    = link_to 'PQRRS Licensing Server', root_path
    online application.
  .btn-toolbar.center
    - if signed_in?
      = link_to 'Dashboard', @signed_in_user, class: 'btn btn-large'
    - else
      = link_to 'Sign up!', signup_path, class: 'btn btn-large btn-primary'
      = link_to 'Sign in', signin_path, class: 'btn btn-large'

app/views/static_pages/how_it_works.haml
- provide :title, 'How it Works'
%legend= yield :title
.row-fluid
  .column.span8
    %section.well
      %legend Description
      %p
        The <strong>PQRRS Licensing Server</strong> is user-oriented backend which allows you to self-generate their licenses for the whole <strong>PQR Recognition Suite</strong>.

    %section.well
      %legend Abstract
      %p
        The fundamentals of this service are based on a few basic rules:
        %ul
          %li Each <strong>device serial number</strong> that is planned to be used along with the PQR Recognition Suite <strong>has to be covered by a license</strong>.
          %li Licenses can be delivered for an <strong>unlimited number of device serial numbers</strong>, along with <strong>any number of software identifiers</strong>.
          %li Once a <strong>license</strong> has been downloaded for a given set of device serial numbers and software identifiers, <strong>these elements cannot be removed</strong> from that license.
  .column.span4
    %section.well
      %legend Example Use
      %ul
        %li
          You create a license with the following elements:
          %ul
            %li Device serials <strong>A</strong> and <strong>B</strong>.
            %li Software identifiers <strong>Product 1</strong> and <strong>Product 2</strong>.
        %li Later, you realize that device serial <strong>A</strong> will not be used within the usage context of this license, so you edit it and remove the device serial <strong>A</strong>.
        %li You also realize that another device will be used within this license context, so you add the device serial <strong>C</strong>.
        %li You download the license information, and start using it.
      At this point, the license is marked as <strong>frozen</strong>, and you will then only be able to add device serial numbers and software to it. Also from this point on, removing anything from the license will be impossible.