config/routes.rb
PQRLicensor::Application.routes.draw do
  # Default landing page.
  root                          to: 'static_pages#home'
  # Rewriting of statics.
  match       '/home',          to: 'static_pages#home'
  match       '/how_it_works',  to: 'static_pages#how_it_works'
  # Rewriting of sign-up / sign-in.
  match       '/signup',        to: 'users#new'
  match       '/signin',        to: 'sessions#new'
  match       '/signout',       to: 'sessions#destroy', via: :delete
  match       '/sessions/my',   to: 'sessions#my'
  resources   :sessions,        only: [ :new, :my, :create, :destroy ]
  # Password resets...
  get         'password_resets/new'
  resources   :password_resets
  # Resources access.
  resources   :sessions,  only: [ :new, :create, :destroy ]
  resources   :users do
    resources   :hardware_tags
    resources   :licenses
  end
  resources   :software_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  include Humanizer

  # Password management stuff.
  has_secure_password

  # Regular accessors.
  attr_accessible       :email, :company_name, :password, :password_confirmation
  attr_accessible       :humanizer_answer, :humanizer_question_id

  def as_json (opts=nil)
    super (opts||{}).merge( { only: [ :email, :company_name, :is_admin ] } )
  end

  attr_accessor         :bypass_humanizer
  require_human_on      :create,
                          unless:       :bypass_humanizer

  # Relationships.
  has_many              :licenses,
                          dependent:    :destroy
  has_many              :software_tags,
                          through:      :licenses
  has_many              :hardware_tags,
                          dependent:    :destroy

  # eMail validation.
  VALID_EMAIL_REGEX     = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates             :email,
                          uniqueness:   { case_sensitive: false },
                          format:       { with: VALID_EMAIL_REGEX, message: 'must be a valid email address' }
  # Company name validation.
  validates             :company_name,
                          length:       { minimum: 5 },
                          uniqueness:   { case_sensitive: false }
  # Password validation.
  VALID_PASSWORD_REGEX  = /^(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){5,40}$/
  validates             :password,
                          format:       {
                            on:       :create,
                            with:     VALID_PASSWORD_REGEX,
                            message:  'must contain at least 5 characters including one lowercase letter and one uppercase letter as well as a digit'
                          }
  validates             :password_confirmation,
                          on:         :create,
                          presence:   true

  before_create         { generate_token_in :remember_token }
  before_save           { self.email.downcase! }

  def is_confirmed?
    created_at!=password_reset_sent_at
  end

  def send_password_reset
    generate_token_in :password_reset_token
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def send_account_creation
    generate_token_in :password_reset_token
    self.password_reset_sent_at = created_at
    save!
    UserMailer.account_creation(self).deliver
  end

  def generate_token_in col
    begin
      self[col] = SecureRandom.urlsafe_base64
    end while User.exists? col => self[col]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include AjaxHelper::Renderer
  before_filter :before_everything,     except: [ :new, :create ]
  before_filter :before_index,          only:   :index
  before_filter :before_new,            only:   [ :new, :create ]
  before_filter :before_existing,       only:   [ :show, :edit, :update, :destroy ]
  before_filter :before_destroy,        only:   :destroy

  # Get users listing.
  def index
    respond_to do |format|
      format.html
      format.js { render_ajax }
      format.json { render json: @users }
    end
  end

  # Shows a single user.
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # User creation form.
  def new
    session[:return_path] = request.referer
    @user = User.new
    respond_to do |format|
      format.html
      format.js { render_ajax }
      format.json { render json: @user }
    end
  end
  # User creation logic.
  def create
    params[:user][:password] = params[:user][:password_confirmation] = "#{SecureRandom.hex(5).upcase}#{SecureRandom.hex(5).downcase}" unless admin_signed_in?
    @user = User.new params[:user]
    @user.bypass_humanizer  = admin_signed_in?
    respond_to do |format|
      if @user.save
        @user.send_account_creation unless admin_signed_in?
        format.html { redirect_to root_path, notice: 'You should have received an email with directions on how to finalize your account creation.' }
        format.js { render_ajax }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.js { render_ajax action: :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # User edition form.
  def edit
    session[:return_path] = request.referer
    respond_to do |format|
      format.html
      format.js { render_ajax }
      format.json { render json: @user }
    end
  end
  # User update logic.
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in @user
        flash[:success] = 'Your profile was updated.'
        format.html { redirect_to session[:return_path] }
        format.js { render_ajax }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.js { render_ajax action: :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # User deletion.
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = 'Account was deleted.'
      format.html { redirect_to users_url, action: :index, success: 'Account was deleted.' }
      format.js { render_ajax }
      format.json { head :no_content }
    end
  end

  private
    # Filter user if not signed in, and stores requested user or authenticated user in @user.
    def before_everything
      store_location and redirect_to signin_path, notice: 'Please sign in.' and return unless signed_in?
    end

    # Deny index to non-admin.
    def before_index
      return redirect_to signed_in_user unless admin_signed_in?
      @users = User.all
    end
    # Deny user creation to non-admin.
    def before_new
      redirect_to (signed_in? ? signed_in_user : root_path), notice: 'Subscriptions are closed.' unless admin_signed_in?
    end
    # Filter user if not viewing current, or if not admin.
    def before_existing
      # Store requested user.
      uid = params[:id].to_i
      @user = signed_in_user.id==uid ? signed_in_user : User.includes([ :licenses, :hardware_tags ]).find(uid)
      redirect_to signed_in_user, notice: 'You are not allowed to access other user\'s profile.' unless signed_in_as?(@user) || admin_signed_in?
    end
    # Destroying should only be done by admin, and they may not delete themselve.
    def before_destroy
      redirect_to signed_in_user, notice: 'You are not allowed to delete users.' unless admin_signed_in?
    end

end

app/views/users/_form.haml
=form_for @user, remote: true, html: { class: 'well form-horizontal' } do |f|
  %fieldset
    %legend #{controller.action_name.capitalize}
    = render 'shared/error_messages', object: @user

    - if admin_signed_in?
      .control-group
        = f.label :email, class: 'control-label'
        .controls
          = f.text_field :email, placeholder: 'me@example.com'
      .control-group
        = f.label :company_name, class: 'control-label'
        .controls
          = f.text_field :company_name, placeholder: 'My Company'

    - elsif @user.new_record?
      .control-group
        = f.label :humanizer_answer, 'Are you human?', class: 'control-label'
        .controls
          = f.text_field :humanizer_answer, placeholder: 'Answer the question below!'
          = f.hidden_field :humanizer_question_id
          .help-block= @user.humanizer_question

    .control-group
      = f.label :password, class: 'control-label'
      .controls
        = f.password_field :password, placeholder: 'Make something up...'
    .control-group
      = f.label :password_confirmation, class: 'control-label'
      .controls
        = f.password_field :password_confirmation, placeholder: 'But be creative!'

    .form-actions
      = f.submit button_text_for(controller), class: 'btn btn-primary'

app/views/users/_user.haml
=content_tag_for :li, user do
  %span.btn-toolbar.pull-right
    %span.btn-group
      - if !signed_in_user?(user)
        = link_to 'Delete', user, method: :delete, remote: true, class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure?' }
    %span.btn-group
      = link_to 'Edit', edit_user_path(user), remote: true, class: 'btn btn-mini' if signed_in?
    %span.btn-group
      = link_to 'Dashboard', user_path(user), class: 'btn btn-primary btn-mini'
  %span.content
    = formated_email_link_for(user).html_safe
  %span.secondary
    = "#{pluralize(user.licenses_count, 'License')}, #{pluralize(user.hardware_tags_count, 'Hardware Tag')}"
    = 'UNCONFIRMED' unless user.is_confirmed?

app/views/users/edit.haml
- provide(:title, 'Account Edition')
.row
  .span8.offset2= render 'form'

app/views/users/index.haml
- provide(:title, 'All Users')
%section.row-fluid
  %h3.span9 Users
  .span3= link_to 'New', new_user_path, remote: true, class: 'btn btn-mini pull-right'
%ul#users.listing= render @users

app/views/users/new.haml
- provide(:title, 'Sign up')
.row
  .span8.offset2= render 'form'

app/views/users/show.haml
- provide(:title, "Profile for #{@user.email}")
.row-fluid
  .column.span5
    %section.row-fluid
      %h3.span9= formated_email_link_for(@user).html_safe
      .span3= link_to 'Edit', edit_user_path(@user), remote: true, class: 'btn btn-mini pull-right'
  .column.span7
    = render 'licenses/licenses_section', user: @user
    = render 'hardware_tags/hardware_tags_section', user: @user