config/routes.rb
PQRLicensor::Application.routes.draw do
  # Default landing page.
  root                          to: 'static_pages#home'
  # Rewriting of statics.
  match       '/home',          to: 'static_pages#home'
  match       '/how_it_works',  to: 'static_pages#how_it_works'
  # Rewriting of sign-up / sign-in.
  match       '/signup',        to: 'users#new'
  match       '/signin',        to: 'sessions#new'
  match       '/signout',       to: 'sessions#destroy', via: :delete
  match       '/sessions/my',   to: 'sessions#my'
  resources   :sessions,        only: [ :new, :my, :create, :destroy ]
  # Password resets...
  get         'password_resets/new'
  resources   :password_resets
  # Resources access.
  resources   :sessions,  only: [ :new, :create, :destroy ]
  resources   :users do
    resources   :hardware_tags
    resources   :licenses
  end
  resources   :software_tags
end

app/models/software_tag.rb
class SoftwareTag < ActiveRecord::Base
  attr_accessible  :name, :identifier, :is_public, :description

  has_many    :software_tags_licenseships
  has_many    :licenses,
                through:      :software_tags_licenseships
  has_many    :hardware_tags,
                through:      :licenses
  has_many    :users,
                through:      :licenses

  validates   :name,
                length:       { minimum: 5 }

  validates   :identifier,
                uniqueness:   true,
                length:       { minimum: 5 },
                format:       { with:   /^[\w.]*$/u, message: 'can only contain alphanumerical characters, dots and spaces.' }

  # Override to_json so the body is hidden.
  def as_json(opts={})
    opts[:only] ||= [ :id, :name ]
    super opts
  end

end

app/controllers/software_tags_controller.rb
class SoftwareTagsController < ApplicationController
  include AjaxHelper::Renderer
  before_filter :before_everything, except: [ :index, :show ]
  before_filter :before_index,      only:   :index
  before_filter :before_existing,   only:   [ :show, :edit, :update, :destroy ]
  before_filter :before_altering,   only:   [ :edit, :update, :destroy ]
  before_filter :before_destroy,    only:   :destroy

  # Get software tags listing.
  def index
    respond_to do |format|
      format.html
      format.js { render_ajax }
      format.json { render :json => @software_tags }
    end
  end
  # Show a single software tag.
  def show
    respond_to do |format|
      format.html
      format.json { render json: @software_tag }
    end
  end
  # Software tag creation form.
  def new
    @software_tag = SoftwareTag.new
    respond_to do |format|
      format.html
      format.js { render_ajax }
      format.json { render json: @software_tag }
    end
  end
  # Software tag creation logic.
  def create
    @software_tag = SoftwareTag.new params[:software_tag]
    respond_to do |format|
      if @software_tag.save
        format.html { redirect_to software_tags_path, notice: 'Software tag was successfully created.' }
        format.js { render_ajax }
        format.json { render json: @software_tag, status: :created, location: @software_tag }
      else
        format.html { render action: :new }
        format.js { render_ajax action: :new }
        format.json { render json: @software_tag.errors, status: :unprocessable_entity }
      end
    end
  end
  # Software tag edition form.
  def edit
    respond_to do |format|
      format.html
      format.js { render_ajax }
      format.json { render json: @software_tag }
    end
  end
  # Software tag edition logic.
  def update
    respond_to do |format|
      if @software_tag.update_attributes(params[:software_tag])
        format.html { redirect_to software_tags_path, notice: 'Software tag was successfully updated.' }
        format.js { render_ajax }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.js { render_ajax action: :edit }
        format.json { render json: @software_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # Software tag deletion logic.
  def destroy
    @software_tag.destroy
    respond_to do |format|
      format.html { redirect_to software_tags_path, action: :index, notice: 'Software tag was successfully deleted.' }
      format.js { render_ajax }
      format.json { head :no_content }
    end
  end

  private
    # Filter user if not signed in.
    def before_everything
      store_location and redirect_to signin_path, notice: 'Please sign in.' and return unless signed_in?
    end
    # Just store hardware tags belonging to current user.
    def before_index
      @software_tags = SoftwareTag.scoped
      @software_tags = @software_tags.where('is_public = ?', true) unless admin_signed_in?
      @software_tags = @software_tags.where('LOWER(name) LIKE ?', "#{params[:search].downcase}%") if params[:search]
    end
    # Stores requested hardware tag.
    def before_existing
      @software_tag = (admin_signed_in? ? SoftwareTag : SoftwareTag.where('is_public = ?', true)).find params[:id]
    end
    # Makes sure user is admin.
    def before_altering
      redirect_to signed_in_user, notice: 'No software tag was found matching your request.' unless admin_signed_in?
    end
    def before_destroy
      redirect_to signed_in_user, notice: 'You are not allowed to delete software tags.' unless admin_signed_in?
    end

end

app/views/software_tags/_form.haml
=form_for @software_tag, remote: true, html: { class: 'well form-horizontal' } do |f|
  %fieldset
    %legend="#{controller.action_name.capitalize} Software Tag"
    =render 'shared/error_messages', object: @software_tag

    .control-group
      =f.label :name, class: 'control-label'
      .controls=f.text_field :name

    .control-group
      =f.label :identifier, class: 'control-label'
      .controls=f.text_field :identifier

    .control-group
      =f.label :is_public, class: 'control-label'
      .controls=f.check_box :is_public

    .control-group
      =f.label :description, class: 'control-label'
      .controls=f.text_area :description, class: 'input-xlarge'

    .form-actions=f.submit button_text_for(controller), class: 'btn btn-primary'

app/views/software_tags/_software_tag.haml
= content_tag_for :li, software_tag do
  %span.btn-toolbar.pull-right
    %span.btn-group
      = link_to 'Delete', software_tag_path(software_tag), remote: true, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Do you really want to delete this Software Tag?' } if admin_signed_in?
    %span.btn-group
      = link_to 'Edit', edit_software_tag_path(software_tag), remote: true, data: { type: :script }, class: 'btn btn-mini' if admin_signed_in?
      = link_to 'Details', software_tag, class: 'btn btn-mini'
  %span.content= link_to software_tag.name, software_tag
  %span.secondary= software_tag.identifier

app/views/software_tags/_software_tags_section.haml
%section.row-fluid
  %h3.span9 Software Tags
  .span3= link_to 'New', new_software_tag_path, remote: true, class: 'btn btn-mini pull-right' if admin_signed_in?
%ul#software_tags.listing= render software_tags

app/views/software_tags/edit.haml
- provide(:title, 'Software Tag Edition')
.row
  .span10.offset1= render 'form'

app/views/software_tags/index.haml
- provide(:title, 'Software Tags')
.row-fluid
  .column.span12= render 'software_tags_section', software_tags: @software_tags

app/views/software_tags/new.haml
- provide :title, 'New Software Tag'
.row
  .span10.offset1= render 'form'

app/views/software_tags/show.haml
- provide :title, @software_tag.name
.row-fluid
  .column.span3.well
    %legend Statistics
    %p So far, this software package is being used...
    %ul
      %li in #{pluralize(@software_tag.licenses.size, 'license')},
      %li along with #{pluralize(@software_tag.hardware_tags.size, 'piece')} of hardware,
      %li by #{pluralize(@software_tag.users.size, 'company')}.
  .column.span9.well
    %legend Description
    = markdown(@software_tag.description).html_safe