config/routes.rb
PQRLicensor::Application.routes.draw do
  # Default landing page.
  root                          to: 'static_pages#home'
  # Rewriting of statics.
  match       '/home',          to: 'static_pages#home'
  match       '/how_it_works',  to: 'static_pages#how_it_works'
  # Rewriting of sign-up / sign-in.
  match       '/signup',        to: 'users#new'
  match       '/signin',        to: 'sessions#new'
  match       '/signout',       to: 'sessions#destroy', via: :delete
  match       '/sessions/my',   to: 'sessions#my'
  resources   :sessions,        only: [ :new, :my, :create, :destroy ]
  # Password resets...
  get         'password_resets/new'
  resources   :password_resets
  # Resources access.
  resources   :sessions,  only: [ :new, :create, :destroy ]
  resources   :users do
    resources   :hardware_tags
    resources   :licenses
  end
  resources   :software_tags
end

app/views/layouts/_footer.haml
%footer
  %small Copyright Pierre qui Roule EURL 2011. All rights reserved.

app/views/layouts/_header.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      = link_to 'PQRRS Licensing Server', root_path, class: 'brand'
      %nav
        %ul.nav
          = nav_link 'Home', home_path
          = nav_link 'Software', software_tags_path
          = nav_link 'How it Works', how_it_works_path
        %ul.nav.pull-right
          = nav_link 'Sign in', signin_path unless signed_in?
          = render 'layouts/user_menu' if signed_in?

app/views/layouts/_user_menu.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    = signed_in_user.company_name
    %b.caret
  %ul.dropdown-menu
    %li= link_to 'Dashboard', signed_in_user
    - if admin_signed_in?
      %li.divider/
      %li= link_to 'Users', users_path
      %li= link_to 'Software', software_tags_path
    %li.divider/
    %li= link_to 'Sign out', signout_path, method: 'delete'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
  </head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">

    <%- flash.each do |key, msg| -%>
      <div id="msg-<%= key %>" class="alert alert-<%= key %>">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <p>
          <%= msg %><br>
        </p>
      </div>
      <script type="text/javascript">
        if('<%= key %>' != 'error') {
          $('#msg-<%= key %>').delay(1500).fadeOut(1000);
        }
      </script>
    <%- end -%>

    <div id="modal-editor" class="modal hide fade">
        <div class="modal-header">
          <a href="#" data-dismiss="modal" class="close">&times;</a>
          <h3>Form</h3>
        </div>
        <div id="modal-editor-body" class="modal-body"></div>
    </div>

    <div id="body-content">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

    <%= debug params if Rails.env.development? %>
  </div>
</body>
</html>